In [ ]:
#### section A

In [2]:
list=[1,2,3,4,5]
list

[1, 2, 3, 4, 5]

In [20]:
list.append(10)
list

[1, 2, 3, 4, 5, 10]

In [22]:
list.extend([25,30])
list

[1, 2, 3, 4, 5, 10, 25, 30]

In [24]:
list.insert(4,22)
list

[1, 2, 3, 4, 22, 5, 10, 25, 30]

In [26]:
list.remove(22)
list

[1, 2, 3, 4, 5, 10, 25, 30]

In [28]:
list.pop()
list

[1, 2, 3, 4, 5, 10, 25]

In [30]:
list.clear()
list

[]

In [34]:
list=[1,2,3,4,5,10,25]
list

[1, 2, 3, 4, 5, 10, 25]

In [38]:
list.index(2)


1

In [42]:
list.append(5)
list

[1, 2, 3, 4, 5, 10, 25, 5]

In [46]:
list.count(5)

2

In [48]:
list

[1, 2, 3, 4, 5, 10, 25, 5]

In [52]:
list.sort()
list

[1, 2, 3, 4, 5, 5, 10, 25]

In [54]:
list.reverse()
list

[25, 10, 5, 5, 4, 3, 2, 1]

In [56]:
### tuple

In [58]:
s=('Abhishek','Adhul','Aswin')
s

('Abhishek', 'Adhul', 'Aswin')

In [66]:
s[2]=('Aatlee')
s[2]

TypeError: 'tuple' object does not support item assignment

In [76]:
#### tuple can't modify,if it modify we have to change the tuple into list then we can easily change the name .

In [70]:
set={1,2,3,3,3,4,5}
set

{1, 2, 3, 4, 5}

In [72]:
### in set the duplicates be vanished while print,beacuse duplicates cannot be form in the set

In [78]:
dict1={'Name': ['Abhishek','Adhul','Aswin'],'Age':[22,22,21],'City':['Banglore','Kerala','Kerala']}
dict1

{'Name': ['Abhishek', 'Adhul', 'Aswin'],
 'Age': [22, 22, 21],
 'City': ['Banglore', 'Kerala', 'Kerala']}

In [102]:
dict1['Age']=25,22,21

In [104]:
dict1

{'Name': ['Abhishek', 'Adhul', 'Aswin'],
 'Age': (25, 22, 21),
 'City': ['Banglore', 'Kerala', 'Kerala']}

In [126]:
dict1.setdefault('email',['aaa.com','bbb.com','ccc.com'])

['aaa.com', 'bbb.com', 'ccc.com']

In [128]:
dict1

{'Name': ['Abhishek', 'Adhul', 'Aswin'],
 'Age': (25, 22, 21),
 'City': ['Banglore', 'Kerala', 'Kerala'],
 'email': ['aaa.com', 'bbb.com', 'ccc.com']}

In [110]:
n=int(input("enter the age"))
age=18
if(Age<=18):
    print(" Not eligible for vote")
else:
    print("Eligible for vote")

enter the age 18


 Not eligible for vote


In [124]:
n=int(input("enter the mark"))
if(n>90):
    print("A")
elif(n>75 or n>89):
    print("B")
elif(n>50 or n>74):
    print("C")
elif(n<50):
    print("Fail")

enter the mark 80


B


In [146]:
n=int(input("enter the number"))
if(n>0):
    print("it is positive number")
elif(n>0 and n%2==0):
    print("it is positive number and even number")
elif(n<0):
    print("it is negative number")
elif(n==0):
    print("it is zero")

enter the number 0


it is zero


In [148]:
#### section B

In [184]:
import numpy as np
import pandas as pd

In [152]:
np.array(5)

array(5)

In [158]:
one_dim=np.array([1,2,3,4,5])
one_dim

array([1, 2, 3, 4, 5])

In [166]:
two_dim=[2,3]
two_dim

[2, 3]

In [176]:
two_dim=np.array([[10,20,30],[40,50,60]])
two_dim

array([[10, 20, 30],
       [40, 50, 60]])

In [178]:
a=np.array(np.random.randint(0,100,16)).reshape(4,4)
a

array([[87, 19, 38, 65],
       [16, 45, 70, 16],
       [10, 89, 19, 66],
       [22, 79, 43, 31]])

In [182]:
s=np.array(np.random.randint(0,100,9).reshape(3,3))
s

array([[15, 95, 75],
       [64,  5, 20],
       [18, 72, 47]])

In [194]:
df=pd.DataFrame(s,columns=('A','B','C'))

In [196]:
df

A   B   C
0  15  95  75
1  64   5  20
2  18  72  47

In [198]:
##### section c

In [200]:
dict={'Name': ['Abhi','Arun','Azi','Anu','Ansi','Amal','Aswin','Adhul','Athu','Aatlee'],
     'Age': [20,21,22,26,22,22,25,45,67,75],
     'City':['Banglore','Kerala','Goa','Kerala','Mumbai','Chennai','NorthEast','Banglore','Goa','Mumbai'],
       'Salary':[10000,20000,30000,45000,50000,55000,60000,50000,60000,89999] }

In [204]:
print(dict)

{'Name': ['Abhi', 'Arun', 'Azi', 'Anu', 'Ansi', 'Amal', 'Aswin', 'Adhul', 'Athu', 'Aatlee'], 'Age': [20, 21, 22, 26, 22, 22, 25, 45, 67, 75], 'City': ['Banglore', 'Kerala', 'Goa', 'Kerala', 'Mumbai', 'Chennai', 'NorthEast', 'Banglore', 'Goa', 'Mumbai'], 'Salary': [10000, 20000, 30000, 45000, 50000, 55000, 60000, 50000, 60000, 89999]}


In [206]:
df1=pd.DataFrame(dict)

In [208]:
df1

Name  Age       City  Salary
0    Abhi   20   Banglore   10000
1    Arun   21     Kerala   20000
2     Azi   22        Goa   30000
3     Anu   26     Kerala   45000
4    Ansi   22     Mumbai   50000
5    Amal   22    Chennai   55000
6   Aswin   25  NorthEast   60000
7   Adhul   45   Banglore   50000
8    Athu   67        Goa   60000
9  Aatlee   75     Mumbai   89999

In [214]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    10 non-null     object
 1   Age     10 non-null     int64 
 2   City    10 non-null     object
 3   Salary  10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes


In [216]:
df1.describe()

Age        Salary
count  10.000000     10.000000
mean   34.500000  46999.900000
std    20.630344  22754.520921
min    20.000000  10000.000000
25%    22.000000  33750.000000
50%    23.500000  50000.000000
75%    40.250000  58750.000000
max    75.000000  89999.000000

In [270]:
df1.iloc[:,[0,2]]

Name       City
0    Abhi   Banglore
1    Arun     Kerala
2     Azi        Goa
3     Anu     Kerala
4    Ansi     Mumbai
5    Amal    Chennai
6   Aswin  NorthEast
7   Adhul   Banglore
8    Athu        Goa
9  Aatlee     Mumbai

In [272]:
df1.drop(columns=['City'])

Name  Age  Salary
0    Abhi   20   10000
1    Arun   21   20000
2     Azi   22   30000
3     Anu   26   45000
4    Ansi   22   50000
5    Amal   22   55000
6   Aswin   25   60000
7   Adhul   45   50000
8    Athu   67   60000
9  Aatlee   75   89999

In [274]:
df1

Name  Age       City  Salary
0    Abhi   20   Banglore   10000
1    Arun   21     Kerala   20000
2     Azi   22        Goa   30000
3     Anu   26     Kerala   45000
4    Ansi   22     Mumbai   50000
5    Amal   22    Chennai   55000
6   Aswin   25  NorthEast   60000
7   Adhul   45   Banglore   50000
8    Athu   67        Goa   60000
9  Aatlee   75     Mumbai   89999

In [278]:
df1.isnull().sum()

Name      0
Age       0
City      0
Salary    0
dtype: int64

In [286]:
df1.duplicated().sum()

0